# Generated by Django 5.0.1 on 2024-03-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bid',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
