# Generated by Django 5.0.1 on 2024-03-18 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auction_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bid',
            field=models.IntegerField(blank=True, default=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BidPrice', to='auctions.bid')),
        ),
    ]
