# Generated by Django 5.0.1 on 2024-03-18 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auction_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidder_name',
            new_name='bidder',
        ),
        migrations.AddField(
            model_name='auction',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
