# Generated by Django 5.0.1 on 2024-03-18 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_rename_bidder_name_bid_bidder_auction_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='bidder',
        ),
    ]
