# Generated by Django 5.0.1 on 2024-03-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_auction_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='isInWatchlist',
            field=models.BooleanField(default=False),
        ),
    ]
