# Generated by Django 5.0.1 on 2024-04-05 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auction_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='watchlist',
        ),
    ]
